services:
  - type: web
    name: server
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
  - type: static
    name: client
    buildCommand: cd client && npm install && npm run build
    publishDir: client/dist
    routes:
      - type: rewrite
        source: /*
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: client
          envVarKey: RENDER_EXTERNAL_URL